# Generated by Django 5.1 on 2024-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_item_category_remove_item_img_url_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default-image.jpg', upload_to='imagenes_raza/'),
        ),
    ]
