# Generated by Django 5.1 on 2024-09-09 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhistory',
            name='date_won',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 8, 0, 0)),
            preserve_default=False,
        ),
    ]
