# Generated by Django 5.1 on 2024-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auctionhistory_date_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhistory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
